// Lightweight mock LLM wrapper for the free-tier promise
async function callLLM(prompt) {
  // In a real setup, you would call a remote LLM API here.
  // For MVP, return a deterministic, parseable JSON string.
  // Example output: {"signal": "BUY", "confidence": 72, "reasoning": "Based on uptrend and rising volume"}
  return JSON.stringify({ signal: 'BUY', confidence: 72, reasoning: 'Demo signal generated by deterministic heuristic for MVP.' })
}

function parseSignalOutput(output) {
  try {
    const data = typeof output === 'string' ? JSON.parse(output) : output
    if (!data || typeof data.signal !== 'string' || !['BUY','SELL','HOLD'].includes(data.signal)) return null
    if (typeof data.confidence !== 'number' || data.confidence < 0 || data.confidence > 100) return null
    if (typeof data.reasoning !== 'string' || data.reasoning.trim().length === 0) return null
    return data
  } catch (e) {
    return null
  }
}

module.exports = {
  callLLM,
  parseSignalOutput
}
